name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download deps
    run: |
      git clone https://github.com/arx8x/CFPropertyList.git
      git clone https://github.com/MatthewPierson/PyBoot.git
      ./make_telnet_rd.php -d iPhone8,4 -b N69AP -v 15.4.1 -s test.shsh

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
